version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ts_prisma_db
    ports:
      - "4000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
